site_name: Klaytn ETL
nav:
  - Overview: index.md
  - Quickstart: quickstart.md
  - Exporting the Blockchain: exporting-the-blockchain.md
  - References:
    - Commands: commands.md
    - Schema: schema.md
    - Limitations: limitations.md
theme: readthedocs
repo_url: https://github.com/klaytn/klaytn-etl
edit_uri: edit/main/docs